# Generated by Django 3.1.2 on 2020-10-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opisan',
            name='boo',
            field=models.BooleanField(default=False),
        ),
    ]
