# Generated by Django 3.1.2 on 2020-11-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_opisan_boo'),
    ]

    operations = [
        migrations.AddField(
            model_name='opisan',
            name='img',
            field=models.ImageField(default='', upload_to='img', verbose_name='Изображение для профиля:'),
        ),
    ]
