# Generated by Django 3.1.4 on 2021-01-02 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_opisan_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new_sg',
            options={'ordering': ['published']},
        ),
        migrations.AddField(
            model_name='new_sg',
            name='opis',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='main.opisan'),
        ),
    ]
