# Generated by Django 3.1.4 on 2021-01-02 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210102_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_sg',
            name='text',
            field=models.TextField(default='', verbose_name='Описание к песни, Ваши соцести и прочее...'),
        ),
        migrations.AlterField(
            model_name='new_sg',
            name='opis',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='main.opisan'),
        ),
        migrations.AlterField(
            model_name='new_sg',
            name='song',
            field=models.CharField(max_length=50, verbose_name='Название трека:'),
        ),
    ]
